SELECT tc.NOME, SUM(QTD_ITEM)
FROM TB_ITEM_VENDA tiv INNER JOIN TB_CLIENTE tc 
ON tiv.CD_CLIENTE_VENDA = tc.CD_CLIENTE 
GROUP BY tc.CD_CLIENTE, tc.NOME 



SELECT tc.NOME, DATA_VENDA 
FROM TB_VENDA tv INNER JOIN TB_CLIENTE tc 
ON tv.CD_CLIENTE = tc.CD_CLIENTE 
ORDER BY DATA_VENDA  





 